
server.port: 8090
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: '*'


spring.security.user.name: 'test-user'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: vega281318
  jpa:
    hibernate:
      ddl-auto: none
